sudo: required
services:
  - docker

before_install:
  - docker build -t eradityajoshi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eradityajoshi/react-test npm test

after_success:
  - docker build -t eradityajoshi/multi-client ./client
  - docker build -t eradityajoshi/multi-nginx ./nginx
  - docker build -t eradityajoshi/multi-server ./server
  - docker build -t eradityajoshi/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #  take image to docker hub
  - docker push eradityajoshi/multi-client
  - docker push eradityajoshi/multi-nginx
  - docker push eradityajoshi/multi-server
  - docker push eradityajoshi/multi-worker
